In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
%matplotlib

Using matplotlib backend: MacOSX


In [2]:
path = "../data/20171013111831-SurveyExport.csv"
df = pd.read_csv("../data/20171013111831-SurveyExport.csv",encoding='cp1252')

/usr/local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2705: DtypeWarning: Columns (24,25,26,27,28,29,30,31,32,33) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
df.head(10)

Response ID   Time Started Date Submitted    Status Language  \
0            1  6/19/17 15:29  6/19/17 15:29  Complete  English   
1            2  7/10/17 13:10  7/10/17 13:10  Complete  English   
2            3   7/20/17 7:21   7/20/17 7:21  Complete  English   
3            4   7/20/17 9:34   7/20/17 9:34  Complete  English   
4            5   7/20/17 9:35   7/20/17 9:35  Complete  English   
5            6   7/20/17 9:36   7/20/17 9:36  Complete  English   
6            7   7/20/17 9:37   7/20/17 9:37  Complete  English   
7            8   7/20/17 9:39   7/20/17 9:39  Complete  English   
8            9  7/20/17 10:03  7/20/17 10:03  Complete  English   
9           10  7/20/17 14:17  7/20/17 14:17  Complete  English   

         Country     Link Name  \
0  USA  Default Link   
1  USA  Default Link   
2  USA  Default Link   
3  USA  Default Link   
4         Canada  Default Link   
5  USA  Default Link   
6  USA  Default Link   
7         Canada  Default Link   
8  USA  Default Link   
9  USA  Default Link   

                                  I consider myself:  \
0  Technically Savvy:   I know my way around a co...   
1  Technically Savvy:   I know my way around a co...   
2  Technically Savvy:   I know my way around a co...   
3  Technically Savvy:   I know my way around a co...   
4  Technically Savvy:   I know my way around a co...   
5  Technically Savvy:   I know my way around a co...   
6  Technically Savvy:   I know my way around a co...   
7           Average User:   I know enough to get by.   
8  Technically Savvy:   I know my way around a co...   
9  Technically Savvy:   I know my way around a co...   

  WiFi Router:Check all the internet connected devices you currently own:  \
0                                        WiFi Router                        
1                                        WiFi Router                        
2                                        WiFi Router                        
3                                        WiFi Router                        
4                                        WiFi Router                        
5                                        WiFi Router                        
6                                        WiFi Router                        
7                                        WiFi Router                        
8                                        WiFi Router                        
9                                        WiFi Router                        

  Laptop computer:Check all the internet connected devices you currently own:  \
0                                    Laptop computer                            
1                                    Laptop computer                            
2                                    Laptop computer                            
3                                    Laptop computer                            
4                                    Laptop computer                            
5                                    Laptop computer                            
6                                    Laptop computer                            
7                                    Laptop computer                            
8                                    Laptop computer                            
9                                    Laptop computer                            

              ...               \
0             ...                
1             ...                
2             ...                
3             ...                
4             ...                
5             ...                
6             ...                
7             ...                
8             ...                
9             ...                

  Connected Devices:Check all the terms below that you could explain to a friend:  \
0                                  Connected Devices                                
1                                  Connected Devices                

In [4]:
df.fillna(0)

Response ID    Time Started  Date Submitted    Status Language  \
0                 1   6/19/17 15:29   6/19/17 15:29  Complete  English   
1                 2   7/10/17 13:10   7/10/17 13:10  Complete  English   
2                 3    7/20/17 7:21    7/20/17 7:21  Complete  English   
3                 4    7/20/17 9:34    7/20/17 9:34  Complete  English   
4                 5    7/20/17 9:35    7/20/17 9:35  Complete  English   
5                 6    7/20/17 9:36    7/20/17 9:36  Complete  English   
6                 7    7/20/17 9:37    7/20/17 9:37  Complete  English   
7                 8    7/20/17 9:39    7/20/17 9:39  Complete  English   
8                 9   7/20/17 10:03   7/20/17 10:03  Complete  English   
9                10   7/20/17 14:17   7/20/17 14:17  Complete  English   
10               11   7/20/17 14:16   7/20/17 14:16  Complete  English   
11               12   7/20/17 14:17   7/20/17 14:17  Complete  English   
12               13   7/20/17 14:18   7/20/17 14:18  Complete  English   
13               14   7/20/17 14:17   7/20/17 14:17  Complete  English   
14               15   7/20/17 14:19   7/20/17 14:19  Complete  English   
15               16   7/23/17 18:52   7/23/17 18:52  Complete  English   
16               17   7/23/17 18:53   7/23/17 18:53  Complete   French   
17               18   7/23/17 18:55   7/23/17 18:55  Complete  English   
18               19   7/24/17 10:33   7/24/17 10:33  Complete  English   
19               20    7/26/17 2:32    7/26/17 2:45  Complete   German   
20               21   7/26/17 12:13   7/26/17 12:16  Complete  English   
21               22   7/27/17 15:23   7/27/17 15:24  Complete    pt-br   
22               23   7/28/17 10:07   7/28/17 10:15  Complete  English   
23               24    7/29/17 0:48    7/29/17 0:53  Complete  English   
24               25   7/29/17 11:21   7/29/17 11:24  Complete   French   
25               26    7/31/17 3:47    7/31/17 3:50  Complete  English   
26               27    7/31/17 9:48    7/31/17 9:50  Complete  English   
27               28     8/1/17 1:07     8/1/17 1:11  Complete   French   
28               29     8/1/17 1:12     8/1/17 1:15  Complete   French   
29               30    8/16/17 0:08    8/16/17 0:12  Complete  English   
...             ...             ...             ...       ...      ...   
192624       192626  10/11/17 20:19  10/11/17 20:24  Complete  English   
192625       192627  10/11/17 20:30  10/11/17 20:32  Complete  English   
192626       192628  10/11/17 20:43  10/11/17 20:44  Complete   French   
192627       192629  10/11/17 21:18  10/11/17 21:27  Complete  English   
192628       192630  10/11/17 22:19  10/11/17 22:29  Complete  Italian   
192629       192631   10/12/17 1:00   10/12/17 1:14  Complete   French   
192630       192632   10/12/17 1:07   10/12/17 1:18  Complete  English   
192631       192633   10/12/17 1:28   10/12/17 1:34  Complete  English   
192632       192634   10/12/17 2:43   10/12/17 2:50  Complete  English   
192633       192635   10/12/17 2:42   10/12/17 2:51  Complete  Italian   
192634       192636   10/12/17 3:09   10/12/17 3:11  Complete    pt-br   
192635       192637   10/12/17 5:16   10/12/17 5:17  Complete  English   
192636       192638   10/12/17 5:53   10/12/17 5:59  Complete   French   
192637       192639   10/12/17 6:49   10/12/17 6:57  Complete  English   
192638       192640   10/12/17 7:12   10/12/17 7:12  Complete  English   
192639       192641   10/12/17 7:26   10/12/17 7:28  Complete   French   
192640       192642   10/12/17 7:32   10/12/17 7:38  Complete    pt-br   
192641       192643   10/12/17 7:41   10/12/17 7:42  Complete  Spanish   
192642       192644   10/12/17 7:43   10/12/17 8:11  Complete  English   
192643       192645   10/12/17 9:29   10/12/17 9:30  Complete  English   
192644       192646   10/12/17 9:59  10/12/17 10:17  Complete  English   
192645       192647  10/12/17 10:59  10/12/17 11:03  Complete  English   
192646      

In [5]:
df['Price:']=df['Price:'].fillna(0)
df['Safety:']=df['Safety:'].fillna(0)
df['Safety:']=df['Safety:'].fillna(0)
df["Price:"]

0         4
1         2
2         2
3         6
4         7
5         1
6         1
7         5
8         1
9         1
10        1
11        9
12        1
13        0
14        5
15        1
16        0
17        0
18        1
19        0
20        0
21        0
22        9
23        4
24        0
25        4
26        6
27        1
28        4
29        0
         ..
192624    1
192625    0
192626    0
192627    3
192628    1
192629    2
192630    8
192631    0
192632    4
192633    3
192634    0
192635    0
192636    4
192637    3
192638    0
192639    0
192640    0
192641    0
192642    1
192643    0
192644    5
192645    4
192646    0
192647    1
192648    4
192649    5
192650    3
192651    1
192652    0
192653    0
Name: Price:, Length: 192654, dtype: object

In [6]:
# x = list()
# for i,row in df.iterrows():
# #     if math.isnan(row["Price:"])  or math.isnan(row["Safety:"]) or math.isnan(row["Safety:"]):
# #         x.append([0,row["Safety:"],row["Features:"],row["Privacy:"]])
#     x.append([int(row["Price:"]),int(row["Safety:"]),int(row["Features:"]),int(row["Privacy:"])])
    
    
    

<h1>asdfadf</h1>



In [7]:
x = np.zeros([len(df),8])
y = np.zeros([len(df),1])

In [8]:
for i,row in df.iterrows():
#     if i <2000:
    for j,t in enumerate(row[36:44]):
#             print(type(x) , x)
        if type(t)== type("asdfa"):
#                 print(j)
            x[i][j] = 1

In [9]:
x

array([[ 1.,  0.,  1., ...,  1.,  1.,  0.],
       [ 1.,  1.,  1., ...,  1.,  1.,  0.],
       [ 1.,  0.,  1., ...,  1.,  0.,  0.],
       ..., 
       [ 1.,  1.,  1., ...,  1.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [10]:
for i,row in df.iterrows():

    if type(row[7])== type("asdfa"):
        if row[7][0] == 'T':
            y[i] = 1
        if row[7][0] == 'A':
            y[i] = 2
        if row[7][0] == 'U':
            y[i] = 3
        if row[7][0] == 'L':
            y[i] = 4

In [11]:
y

array([[ 1.],
       [ 1.],
       [ 1.],
       ..., 
       [ 1.],
       [ 1.],
       [ 0.]])

In [12]:
s =0.7
split = int(s*len(df))

x_train = x[split:]
y_train = y[split:]

x_test = x[:split]
y_test = y[:split]

In [13]:
model = np.linalg.inv(np.transpose(x_test).dot(x_test)).dot(np.transpose(x_test).dot(y_test))

In [14]:
model.shape


(8, 1)

In [15]:
model


array([[ 0.07872505],
       [ 0.15220595],
       [ 0.27542796],
       [ 0.03216647],
       [ 0.10944953],
       [ 1.17391907],
       [ 0.27239566],
       [ 2.09777008]])

In [16]:
pred=x_train.dot(model)

In [17]:
pred = np.round(pred)

In [18]:
np.std(pred-y_train)

1.1752042623519101

In [19]:
from sklearn.neural_network import MLPClassifier

In [20]:
clf = MLPClassifier(solver='adam', alpha=1e-5,hidden_layer_sizes=(128, 128), random_state=1,early_stopping=True,verbose=True)

In [21]:
clf.fit(x_test,y_test)

/usr/local/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:912: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(128, 128), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [22]:
mlp_pred = clf.predict(x_train)

In [23]:
# np.std(mlp_pred-y_train)

KeyboardInterrupt: 

In [ ]:
clf.score(x_train,y_train)

In [ ]:
weights = np.zeros([8,1])
for i,value in enumerate(clf.coefs_[0]):
    weights[i]= np.sum(value)

In [ ]:
weights

In [ ]:
Values =["BotNet","Blockchain","RFID","DDOS","ZeroDay"
        ,"VPN","TOR","NoIdea"]

In [ ]:
for x,y in zip(Values,weights):
    print(x,y)